### ISSUE TITLE
zoomeyeserch.py fails to parse anything.

### ISSUE THREAD

**Issue by gitxmax** [starnightcyber/ZoomEye#1]
Modified the file with my zoomeye credentials, chmodded to +x, on execution, it parses the api key just fine, but fails to parse any data.
Also, the search.txt is not actually created.

python zoomeyeserch.py -t host -q searchxxx-f search.txt

{"access_token": "myapi"}
There are 250 pages to fetch
Page 0 ,  Error exit...
Page 1 ,  Error exit...
Page 2 ,  Error exit...
..........
Page 250 ,  Error exit...
The result in search.txt

Please help, if possible.
Thanks!

**Comment by starnightcyber** [comment]
try to use script getZoomEyeIpList.py, they do the same thing, modify the script as you like. 
may i ask what system are you using?
